# Generated by Django 3.2.20 on 2023-09-01 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('screenshots', models.ImageField(upload_to='project_screenshots/')),
                ('technologies_used', models.CharField(max_length=255)),
                ('project_url', models.URLField()),
            ],
        ),
    ]
