# Generated by Django 3.2.20 on 2023-09-02 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='file',
            field=models.ImageField(upload_to='resume/'),
        ),
    ]
